version: "3.7"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

include:
  - ../common/proxy.yml

services:
  ui:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../../.:/app/.
      - /app/node_modules/
    command: sh -c "npm i && npm run dev"
    environment:
      - NEXT_PUBLIC_SUBLINKS_API_BASE_URL=sublinks:8080
      - NEXT_PUBLIC_SUBLINKS_API_BASE_PUBLIC_URL=localhost
      - NEXT_PUBLIC_HTTPS_ENABLED=false
      - WATCHPACK_POLLING=true
    restart: always
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1
      start_period: 10s
      interval: 30s
      timeout: 60s
      retries: 3
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy
      federation:
        condition: service_healthy
    logging: *default-logging

