version: "3.7"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

services:
  seeder:
    image: node:20-alpine
    working_dir: /job
    volumes:
      - ../common/seeder/.:/job/.
    command: sh -c "npm i && npm run seed"
    environment:
      - NEXT_PUBLIC_SUBLINKS_API_BASE_URL=http://${API_HOST:-api}:8080
    logging: *default-logging
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      api:
        condition: service_healthy
