version: "3.7"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

services:
  federation:
    image: ghcr.io/sublinks/sublinks-federation:main
    restart: always
    environment:
      DB_TYPE: "postgres"
      DB_DSN: "postgres://federation:federation@localhost:5432/federation?sslmode=disable"
      AMQP_SERVER_URL: "amqp://sublinks:sublinks@queue:5672"
      HOSTNAME: sublinks.org
      LISTEN_ADDR: ":8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 15s
      timeout: 10s
      retries: 10
    depends_on:
      maindb:
        condition: service_healthy
      queue:
        condition: service_healthy
    logging: *default-logging

