volumes:
  letsencrypt:

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

services:
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      CERTBOT_EMAIL: developer@example.com
      USE_LOCAL_CA: 1
      STAGING: 1
      NGINX_ENTRYPOINT_WORKER_PROCESSES_AUTOTUNE: 1
      API_HOST: ${API_HOST:-api}
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./nginx/nginx_internal.conf:/etc/nginx/user_conf.d/nginx.conf:ro,Z
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro,Z
      - letsencrypt:/etc/letsencrypt
    restart: always
    logging: *default-logging
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      ui:
        condition: service_healthy
